### ISSUE TITLE
[Request] Add support for EnderIO Tank recipes

### ISSUE THREAD

**Issue by Fireztonez** [Shadows-of-Fire/EnderTweaker#1]
Hello,
Can you add possibility to  add or remove recipes for the EnderIO Tank please, in EnderTweaker for Minecraft 1.12.2??

This is already a thing with the XML file, so I think this is probably possibly for you to add with the EnderIO API...

Thank's
Fireztonez

**Comment by Shadows-of-Fire** [comment]
I didnt even realize tanks had recipes.

But I should be able to add support for them if the xml supports it.

**Comment by Fireztonez** [comment]
Ok, nice!
Thank's
