### ISSUE TITLE
SAG Mill Recipe Error

### ISSUE THREAD

**Issue by Jerome226** [Shadows-of-Fire/EnderTweaker#14]
Why does it work, but when I join a world it puts me this error : 
[ERROR] recipes_changes.zs:2005 > could not find NONE;

My script :
mods.enderio.SagMill.addRecipe([<immersiveengineering:material:17>], [100], <ore:fuelCoke>, NONE, 4600);

**Comment by ElektroKill** [comment]
you have to make NONE a string like this: "NONE"

**Comment by Jerome226** [comment]
Old issue anyways, i'm gonna close this.
