### ISSUE TITLE
ET 1.2.0 not yet Compatible with EIO 5.2.60

### ISSUE THREAD

**Issue by Speecker** [Shadows-of-Fire/EnderTweaker#18]
Heya ;)
Hope I reach you here.
See my Post on Curseforge.
EnderIO Updated quite a lot and their current build is much more stable and more performant then the older ones.
I always update and handcraft compatibility for my own Version of PO3 and the current version of ET 1.2.0 just supports up to EIO 5.1.53.
I think not just PO3 OG will benefit from an update to EIO 5.2.60.
Most Recipes are heavily dependent on ET (especially in Kappa Mode).
Almost every EnderIO recipe for Kappa mode is being changed through ET and therefore will be broken (Items aren’t craftable/producible anymore and the basic recipes brake the game difficulty and EMC values significantly).
Hope we can count on an update to EIO 5.2.60 Soon.
Bless your work with the CraftTweaker integration of EIO so far 👍

**Comment by Shadows-of-Fire** [comment]
I have no intention of updating any mods for versions below 1.15.2 anymore.  It would take too much time that I do not have.

**Comment by Speecker** [comment]
Sad to hear that but understandable.
So may there ever be an update for 1.12.2-5.2.60 EIO or is it final that it won’t see any update ?

**Comment by Shadows-of-Fire** [comment]
Someone could PR the changes in, but I do not have time for 1.12 development, and this mod in particular is rather difficult to update on it's own.

**Comment by ALongStringOfNumbers** [comment]
There is now a PR for the update to newer Ender IO versions: https://github.com/Shadows-of-Fire/EnderTweaker/pull/20
Since CurseForge is going read only tomorrow, is there any chance that this PR could be integrated and then a new version published on CurseForge after it exits Read Only status?

**Comment by Shadows-of-Fire** [comment]
I am currently away from my primary machine so I will probably be unlikely to merge and build before the readonly state begins (hence why I have not done so thus far).

**Comment by ALongStringOfNumbers** [comment]
Thanks for the update.

**Comment by NordicGamerFE** [comment]
@ALongStringOfNumbers Its going read only but with feedback they have accepted to still accept updates on live projects
