### ISSUE TITLE
Crafttweaker Alloy Smelter recipes dont seem to work

### ISSUE THREAD

**Issue by Filostorm** [Shadows-of-Fire/EnderTweaker#23]
Not sure where the problem lies exactly, but here makes the most sense. 

The recipes show up in JEI, but don't work.

**Comment by NeutronSelector** [comment]
Same for me. 
I reported this problem to Elektrokill, but for now i have no answer.

With XML recipes from EIO, it works. The problem stems from EnderTweaker.

**Comment by Filostorm** [comment]
Mind pasting an example xml script for alloys?

**Comment by NeutronSelector** [comment]
#24 Does not work. Same behavior.

@Filostorm here is an example of XML for AlloySmelter
`<recipe name="Smelt: Iron ore" required="false">`
    `<alloying energy="9000" exp="0.0">`
    `<input name="exnihilocreatio:item_ore_iron:1"/>`
    `<output name="minecraft:iron_ingot" amount="3"/>`
    `</alloying>`
`</recipe>`

You have other example in sources of EIO

**Comment by ElektroKill** [comment]
Sorry to tell, but I can’t figure out how to get enderio to add an alloy smelter recipe which has only one input. It works with 2 and 3 inputs but can’t get it to work with 1 :/

**Comment by Filostorm** [comment]
Wouldn't that just be normal smelting though?

**Comment by NeutronSelector** [comment]
It is true that I did not try to make an aliage.
It seems to me that there has been a change with the recipes with only one entry.
While doing my tests with XML from EIO, I noticed that the AlloySmelter melts 3 by 3 (even for tier 1) and no longer 1 by 1. And this is not the case for the alloys.
I don't know if this can help or not ...
