### ISSUE TITLE
Add Support for Machine Restriction

### ISSUE THREAD

**Issue by TwilightPSN** [Shadows-of-Fire/EnderTweaker#4]
Make it so you can have certain recipes not be doable in simple versions of the machines. The base ender io has some recipes that can only be done in the industrial/enhanced version of the machines.

**Comment by Shadows-of-Fire** [comment]
Sadly, this recipe system doesn't appear to support that very well.  The RecipeLevel setup as a whole is only implemented for the Tank (the normal tank has level NORMAL and the pressurized has ADVANCED).

The other machines all return RecipeLevel.IGNORE for their levels, so they cannot be used to determine anything based on level.
The exceptions in EnderIO are not special recipes, it's only the vanilla furnace recipes that are blocked from processing in the Simple Alloy Smelter.
