### ISSUE TITLE
Alloy Smelter recipes don't allow oredict inputs with quantity >1

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/EnderTweaker#5]
```
mods.enderio.AlloySmelter.addRecipe(<metallurgy:damascus_steel_ingot>*3, [<ore:ingotBronze>*2, <ore:ingotIron>]);
```
Will ignore the '*2' and register as: 1 bronze + 1 iron -> 3 damascus steel

However, if I use specific IItemStacks for the input like below then it works fine
```
mods.enderio.AlloySmelter.addRecipe(<metallurgy:damascus_steel_ingot>*3,[<nuclearcraft:alloy>*2,<minecraft:iron_ingot>]);
```

I can work around this obviously, but it is a bug

**Comment by Shadows-of-Fire** [comment]
This appears to be a bug in CraftTweaker.  When converting an IIngredient with a count to a normal Ingredient, it discards the stacksize.  I've mentioned it to them, so hopefully they resolve it quickly.
