### ISSUE TITLE
[Request] Adding possibility to remove recipes by name

### ISSUE THREAD

**Issue by Fireztonez** [Shadows-of-Fire/EnderTweaker#6]
Hello, can you add a possibility to remove machine recipes by the name of recipes (All recipes have a unique name) or at least by input + output, question to be able to remove an alloy recipes, without removing all the recipes with the same output??

Thank's

**Comment by Shadows-of-Fire** [comment]
The recipes don't appear to have a name in-code (at least not one that's exposed), so I'll look into per-input removal.

**Comment by Shadows-of-Fire** [comment]
<https://github.com/Shadows-of-Fire/EnderTweaker/blob/master/Documentation.md#recipe-removal>
ET 1.1.5

**Comment by Fireztonez** [comment]
Thank'you for adding that function, this is perfect for me!

Continue your great work, you're amazing!
