### ISSUE TITLE
SagMill extra output weights don't work.

### ISSUE THREAD

**Issue by Renari** [Shadows-of-Fire/EnderTweaker#8]
According to the docs the syntax of the command is like so:
```
mods.enderio.SagMill.addRecipe(IItemStack[] output, float[] chances, IIngredient input, @Optional String bonusType, @Optional int energyCost, @Optional float[] xp);

mods.enderio.SagMill.addRecipe([<minecraft:planks>], [100], <minecraft:log>);
```

So the following should add `minecraft:wheat` -> `vanillafoodpantry:flour_portion` with a 20% chance for `minecraft:wheat_seeds`.
```
SagMill.addRecipe([<vanillafoodpantry:flour_portion>, <minecraft:wheat_seeds>], [100, 20], <minecraft:wheat>);
```
However in-game the 20% chance for the `minecraft:wheat_seeds` is actually outputting 100% of the time.

**Comment by Shadows-of-Fire** [comment]
The floats should be decimals, 20 is treated as 2000% in this case.  Use 0.2 for 20%

**Comment by Renari** [comment]
https://crafttweaker.readthedocs.io/en/latest/#Mods/Ender_Tweaker/SAG_Mill/

The docs here should show that then, rather than using integers which is misleading.

**Comment by Shadows-of-Fire** [comment]
I did not make those.  The only official documentation for EnderTweaker is [the one here on Github](https://github.com/Shadows-of-Fire/EnderTweaker/blob/master/Documentation.md)

**Comment by Renari** [comment]
Alright, thanks.
