### ISSUE TITLE
Mod causes game to crash on startup. had no previous issues

### ISSUE THREAD

**Issue by Sweddy** [Shadows-of-Fire/EnderTweaker#9]
I have a pretty hefty CraftTweaker script (that's still unfinished) and Ender Tweaker has worked fine up until this point. Now, suddenly, even though I added no new EnderIO-related recipes since my previous startup, the game crashes and blames Ender Tweaker. This was with the mod version 1.1.4.
  I removed the mod, and doing so allowed the game to start with no errors or crashes. I then downloaded and installed the new 1.1.5 version of the mod, at which point the game crashed on startup once again. 
  The crash is then definitely caused by Ender Tweaker and I don't know why. I can provide the crash report and other necessary files if asked. Please help.

**Comment by Shadows-of-Fire** [comment]
crash reports are required to debug anything, so, put that on gist and link it

**Comment by Sweddy** [comment]
I just realised I did make an adjustment to an EnderIO recipe. I attempted to remove the recipe for the Decay enchantment book in the Enchanter and add a new one. Doing so allowed me to start the game normally. Nonetheless, [here is the crash report](https://gist.github.com/Sweddy/2b7a81cd7ca3d9709ba1f1d9c6695b89).

**Comment by Shadows-of-Fire** [comment]
That's an error with your script, obviously the error handling is bad on ET's end (and will be improved shortly), but it's not an actual bug.  You've either got a null reference to the enchantment object, or to the ingredient for the recipe addition.
